### ISSUE TITLE
PatchWork Singapore

### ISSUE THREAD

**Issue by chernjie** [GrumpyGits/grumpygits.github.io#5]
Learning open source, together
(based on Github's PatchWork by @jlord) 

Patchwork is a hands on workshop for learning Git and GitHub. There will be snacks for hackin', lots to learn, and new friends to be made. We'll have GitHubbers and other open source contributors as mentors to lend a hand as attendees make their way through the workshop.

**When?**
- [ ] Saturday, May 30th at 2:30pm - 5:30pm
- [ ] Saturday, Jun 6th at 2:30pm - 5:30pm

**Where?**
- [ ] TBD
- [ ] somewhere that fits 100 people and laptops with internet connection

**Tasks:** 
- [ ] Gather attendees and mentors

cc: @winston
